一般公開の理由などについて
januswel/zenn-contents pull request #12
Opened 2023-04-25 16:05 UTC by YutamaKotaro

草案なので細かいところはチェックしてません。なので、誤字脱字などについては目を瞑っていただけますと幸いです（拾っていただけたらそれはそれで幸いです 🙇🏻 )

- この流れでよいのか？
- 追加したい項目

などなどあればお教えください。

2023-04-27 05:03 UTC, januswel approved these changes
契約終了の期日が出版から 3 年後の 2023/04 末であること、これのみ修正してもらえればばっちりです！
非常にエモくて一気に読んじゃいました
ありがとうございます

2023-04-27 12:09 UTC, nitaking commented on articles/hello.md
> +時の流れは早いもので、この本を出版したのは2020年の5月30日と今から遡ること約４年前の出来事です。当時はコロナウイルスによる様々な影響があり、出版予定から約一ヶ月を過ぎてから出版がされました。そのため2024年の４月末をもって出版契約の有効期限の更新日がやってきました。
未来に生きてたのちょっと笑いました

2023-04-27 12:12 UTC, nitaking approved these changes
エモエモで超絶良きなんですが！

GWにこれに追撃してアンサーソング的な感想ブログ書いたろうかなって思う程に刺さりました。笑

2023-04-27 12:12 UTC, nitaking commented on articles/hello.md
> +仁田さん　は僕が師匠（上司）に当たるパターンで、日々仕事に追われる毎日を共に乗り越えた仲間でもあります。初めてあった時は、まだ始めたてということもあり、そこまでweb界隈に関する知識はなかったものの、キャッチアップの能力は素晴らしいものがあり、いきなり大きな仕事（それこそSwiftアプリのReact Naive化）をぶん投げるという僕の無茶振りにもしっかりとついてきてくれました。そして、お恥ずか
まじ姑コメントで失礼なんですけど、冒頭の`にたさん`と`仁田さん`の表記ゆれ、にたさん でいい気がしました。笑

2023-05-08 12:01 UTC, januswel requested changes
西原さんからのお返事に対応お願いします！

2023-05-08 12:01 UTC, januswel commented on articles/hello.md
> +https://gihyo.jp/site/inquiry/manuscript
URL は出さないようにとのことでしたので、削りましょう

2023-05-09 13:56 UTC, YutamaKotaro commented on articles/hello.md
> +そこで同著者である　[やぬすさん]()の提案、[にたさん]()の同意により、『**契約を解除し一般公開をする**』という決断をすることになりました。この件に関しては出版元である**技術評論社様**にも相談をさせていただき、快く了承をいただきました。
そうですねぇ・・・・そうします！

2023-05-09 14:20 UTC, YutamaKotaro commented on articles/hello.md
> +https://gihyo.jp/site/inquiry/manuscript
はい！

2023-05-14 14:32 UTC, YutamaKotaro commented on articles/hello.md
> +時の流れは早いもので、この本を出版したのは2020年の5月30日と今から遡ること約４年前の出来事です。当時はコロナウイルスによる様々な影響があり、出版予定から約一ヶ月を過ぎてから出版がされました。そのため2024年の４月末をもって出版契約の有効期限の更新日がやってきました。
wwww 今2024年だと思ってました笑

2023-05-15 00:16 UTC, januswel approved these changes
いいですね！

2023-05-15 00:16 UTC, januswel commented on articles/hello.md
> +なかなかない機会なので『**執筆の経緯**』や『**商業誌を執筆した経験について**』など、今後商業誌を書きたいと思う方へ向けて参考なったらと思い・・・また、多くの方へ商業誌を書いてみたいと思っていただけるように・・・誠に勝手ながら思いの方も書かせていただけたらと思っております🙇🙇
参考なったらと思い
↓
参考**に**なったらと思い

2023-05-15 11:48 UTC, nitaking approved these changes
🥳🤟🥳

2023-05-15 11:48 UTC, nitaking commented on articles/hello.md
> +そこで同著者である　[やぬすさん](https://twitter.com/janus_wel)の提案、[にたさん](https://twitter.com/nitaking_)の同意により、『**契約を解除し一般公開をする**』という決断をすることになりました。この件に関しては出版元である**技術評論社様**にも相談をさせていただき、わがままを了承をいただきました。
リンクあざます！

2023-05-16 00:14 UTC, januswel commented on articles/hello.md
> +いい画像見つけて小さくしたい
```
![alt text](image.png =360x)
```

Zenn では最後に横幅を px で指定することが可能です

https://zenn.dev/zenn/articles/markdown-guide#%E7%94%BB%E5%83%8F%E3%81%AE%E6%A8%AA%E5%B9%85%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%99%E3%82%8B

2023-05-16 04:34 UTC, nitaking commented on articles/hello.md
> +いい画像見つけて小さくしたい
素材からお求めということなら unsplash でいくつか適当に book で拾いました

https://images.unsplash.com/photo-1481627834876-b7833e8f5570?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMXwwfDF8c2VhcmNofDV8fGJvb2t8ZW58MHx8fHwxNjg0MTY3MTYyfDA&ixlib=rb-4.0.3&q=80&w=200
https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMXwwfDF8c2VhcmNofDR8fGJvb2t8ZW58MHx8fHwxNjg0MTY3MTYyfDA&ixlib=rb-4.0.3&q=80&w=200
https://images.unsplash.com/photo-1594312915251-48db9280c8f1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMXwwfDF8c2VhcmNofDIxfHxib29rfGVufDB8fHx8MTY4NDE2NzE2Mnww&ixlib=rb-4.0.3&q=80&w=200
https://images.unsplash.com/photo-1476275466078-4007374efbbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMXwwfDF8c2VhcmNofDI0fHxib29rfGVufDB8fHx8MTY4NDE2NzE2Mnww&ixlib=rb-4.0.3&q=80&w=200

2023-05-16 15:57 UTC, YutamaKotaro commented on articles/hello.md
> +いい画像見つけて小さくしたい
ごめんなさい、ここ残したままでした・・・！！
ありがとうございます！

2023-05-18 03:02 UTC, januswel commented
公開された

https://zenn.dev/yutama_kotaro/articles/dd30e429693977

2023-05-18 03:07 UTC, januswel commented
#16 , #17 で本からもリンクしたのでこれは閉じる

2023-05-18 03:07 UTC, closed without merging